### ISSUE TITLE
Disallowed Key Characters.

### ISSUE THREAD

**Issue by LeOSW42** [YunoHost-Apps/agendav_ynh#10]
Once installed, I have that error displayed while selecting this application :

Disallowed Key Characters.

**Comment by anmol26s** [comment]
Hi @LeOSW42 
Deleting the browser cookies would solve the issue.

Thanks

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/521

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
