### ISSUE TITLE
403 Forbidden when on a subdomain

### ISSUE THREAD

**Issue by s0r00t** [YunoHost-Apps/agendav_ynh#12]
Test case :
-Create another subdomain (here, dav.domain.tld)
-Install AgenDAV on it

Expected : Working AgenDAV.
Results : 403 Forbidden

[This issue also happens with Baikal.](https://github.com/julienmalik/baikal_ynh/issues/8)

**Comment by stevenroose** [comment]
Is this being looked at?

**Comment by julienmalik** [comment]
Closed by https://github.com/julienmalik/agendav_ynh/commit/dcda7bb40bd291fa69d97215f3c65b38e74bbdf3

**Comment by stevenroose** [comment]
Can we get it working by simply updating?

**Comment by julienmalik** [comment]
Sure ! The modification is already deployed.

**Comment by julienmalik** [comment]
I must admit, I only tested the modification on baikal, not on agendav. But as it was the same cause, this should be ok. Thanks in advance for confirming here !

**Comment by stevenroose** [comment]
I get the following nginx error:
```
2015/08/04 01:51:06 [emerg] 2839#0: invalid number of arguments in "location" directive in /etc/nginx/conf.d/agenda.roose.ch.d/agendav.conf:1
```
Here is my complete error.log: 
https://gist.github.com/anonymous/10439f4583b0cb5f7874

**Comment by julienmalik** [comment]
must be a bug in the update script...

**Comment by stevenroose** [comment]
I don't know what this line does
`caldavpath=${caldavpath%/}`
When used on a subdomain, the path is '/'.

**Comment by stevenroose** [comment]
I think I found the error.
Look at the nginx conf file: https://gist.github.com/anonymous/d8b72de853e8b73fd684

It has `location  {` instead of `location / {`.

**Comment by stevenroose** [comment]
However just changing that line doesn't seem to fix the issue.

**Comment by stevenroose** [comment]
Well, it did work after the change (after I added the `/`).

There was just another error in the baikal file (I uncommented the `.well-known/` urls and the rewrite rule was wrong

**Comment by stevenroose** [comment]
I got this fixed, I'll PR the fix next week. If I forget, feel free to ping me :)

**Comment by Kloadut** [comment]
Ping @stevenroose ? :D

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/520

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
