### ISSUE TITLE
Got a database error

### ISSUE THREAD

**Issue by stevenroose** [YunoHost-Apps/agendav_ynh#13]
The CalDAV works fine on my desktop client, so Baikal's not at fault

Should I report this with the Agendav devs, or is it a config issue?

This is what I get:
```
A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: core/Loader.php

Line Number: 346
```
I think it's about this line: https://github.com/julienmalik/agendav_ynh/blob/master/sources/web/system/core/Loader.php#L346

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/519

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
