### ISSUE TITLE
Transfert d'évènement "all day" google vers agenDAV via Thunderbird cassé

### ISSUE THREAD

**Issue by superllm** [YunoHost-Apps/agendav_ynh#14]
Étapes pour reproduire :

- Créer un événement "all day" dans un calendrier Google
- Synchroniser l'agenda dans Thunderbird
- Synchroniser l'agenda AgenDAV/Baikal dans Thunderbird
- Éditer l'événement du calendrier Google dans Thunderbird pour le déplacer dans l'agenda Baikal
- Consulter au niveau de l'événement AgenDAV

Message d'erreur dans l'interface, en raison d'une erreur 500. Le message d'erreur dans nginx correspondant est :

<addr>2015/10/21 16:03:30 [error] 32402#0: *21983 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function diff() on boolean in 
                  /var/www/agendav/web/application/libraries/Icshelper.php on line 404" while reading response header from upstream, [...]</addr>

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/518

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
