### ISSUE TITLE
agendav language not applied

### ISSUE THREAD

**Issue by Fabdefab** [YunoHost-Apps/agendav_ynh#31]
Hello 

i try to change agendav language to french.
setting page change in french but not agenda page.
it's stay in english.
setting : 
var/www/agendav/web/config# grep -A2 "languajge" settings.php
// Default languajge
$app['defaults.language'] = 'fr_FR';

/var/www/agendav/web/config# ls -ls
total 24
8 -rw-rwx--- 1 root agendav 4144 mai   23  2017 default.settings.php
4 -rw-rwx--- 1 root agendav  335 mai   23  2017 dev.php
4 -rw-rwx--- 1 root agendav  680 mai   23  2017 languages.php
4 -rw-rwx--- 1 root agendav 1377 mai   23  2017 prod.php
4 -rw-r-x--- 1 root agendav 3280 oct.  16 23:52 settings.php

french language was selected when installed apps.
Do you know where i can change setting for apply french language.

thanks
Fabien

**Comment by anmol26s** [comment]
Maybe reload php and clear cache?
