### ISSUE TITLE
Fix Install on HTTP2

### ISSUE THREAD

**Issue by liberodark** [YunoHost-Apps/agendav_ynh#32]
https://github.com/YunoHost/yunohost/pull/578#discussion_r235645842

Not work is listed on app need fix on script install

**Comment by decentral1se** [comment]
OK, given that https://github.com/YunoHost/yunohost/pull/578 is closed, should we also close here?

**Comment by kay0u** [comment]
I think so.

Thank you for this report, feel free to reopen it if needed!
