### ISSUE TITLE
Posssibility to copy events (feature request)?

### ISSUE THREAD

**Issue by CuriousCocainist** [YunoHost-Apps/agendav_ynh#41]
I have to stress that the possibility to modify single events from the repeating series is a fantastic step up in relation to a standard nextcloud calendar :+1: 

As in the title, I was wondering if it's possible to introduce an option to copy/duplicate calendar event. It's nicely implemented in google calendar, where "duplicate" option, after clicking an existing event, opens edition window filled with its details, although introduced changes crate a new event.

Pretty useful for my purposes (e.g. saving repeated lectures for different subjects) and would be even more perfect under the right-click... I've no idea though if ajax allows such interactions so please disregard if I'm talking rubbish.

**Comment by decentral1se** [comment]
Hey @CuriousCocainist! That sounds like a request to the application developers and not the application packagers here :) See https://github.com/agendav/agendav for raising an issue there :+1:

**Comment by CuriousCocainist** [comment]
@decentral1se You're very right, pardon for this incompetence of mine ;) 
I'll ask/suggest at the source
