### ISSUE TITLE
installation failure

### ISSUE THREAD

**Issue by deepdarkpurple** [YunoHost-Apps/agendav_ynh#42]
Hello-

I just tried installing agenDAV over a Yunohost installation. It failed, unfortunately.

The log dump is available [at this URL](https://paste.yunohost.org/raw/kecezijadi)

Any help would be appreciated.

Cheers,

Eric

**Comment by novadeviator** [comment]
same thing here..

Log is here: https://paste.yunohost.org/raw/qiquwubehi

**Comment by novadeviator** [comment]
Oh, I just noticed, both of these logs contain error that Baikal or Radicale should be installed. Why is this prerequisite? I want to use a different server for CalDAV, can't agendav function as an independent client for a remote CalDAV server?

**Comment by novadeviator** [comment]
I have install Baikal and then AgenDAV was installed flawlessly. But by using it, I realised AgenDAV does not support other hosts than the one CalDAV server on your yunohost installation. This should be more clear in the description of the package.
