### ISSUE TITLE
Error about php version?

### ISSUE THREAD

**Issue by Jojo144** [YunoHost-Apps/agendav_ynh#52]
If I understand correctly https://github.com/YunoHost-Apps/agendav_ynh/commit/64f09e4aaf7f64a0989744a5652426c42bc90b2a , the php version used is 7.3.

But in [manifest.json](https://github.com/YunoHost-Apps/agendav_ynh/blob/testing/manifest.json) we can read:

```
    "services": [
        "nginx",
        "php7.0-fpm",
        "mysql"
    ],
```

Is it a mistake?

**Comment by ericgaspar** [comment]
This is not where PHP version isset. this bit declares de services used by the app (I think there is no much uses in these lines...) but maybe I am wrong.

**Comment by alexAubin** [comment]
(Yeah these lines are not really used for anything apart from checking that these services are up before running the install or upgrade ... Additionally, Yunohost magically replaces occurrences of php7.0 by php7.3)
